WordCounter/WordCounter/Models/ErrorViewModel.cs
using System;

namespace WordCounter.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WordCounter/WordCounter/Controllers/UploadFileController.cs
using Grpc.Core;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using WordCounter.Model;
using X.PagedList;

namespace WordCounter.Controllers
{
    public class UploadFileController : Controller
    {
        [Obsolete]
        private IHostingEnvironment Environment;
        private DBContext db=new DBContext();
        private static readonly int pageSize = 20;

        [Obsolete]
        public UploadFileController(IHostingEnvironment _environment)
        {
            Environment = _environment;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult DisplayData(string sortOrder, int? page)
        {
            int pageNumber = (page ?? 1);
            ViewBag.SortOrder = sortOrder;
            IQueryable<WordModel> wordList = db.WordModels;

            wordList = sortOrder switch
            {
                "FrequencyASC" => wordList.OrderBy(x => x.Frequency).ThenBy(x => x.Word),
                "WordASC" => wordList.OrderBy(x => x.Word),
                "WordDESC" => wordList.OrderByDescending(x => x.Word),
                _ => wordList.OrderByDescending(x => x.Frequency).ThenBy(x => x.Word),
            };
            

            return View("Index", wordList.ToPagedList(pageNumber, pageSize));
        }
        

        [HttpPost]
        [Obsolete]
        public IActionResult Upload(IFormFile postedFile)
        {
            List<WordModel> wordList = new List<WordModel>();
            try
            {
                /*Prepare a local directory to upload file*/
                string wwwPath = Environment.WebRootPath;
                string path = Path.Combine(Environment.WebRootPath, "Uploads");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                
                
                /*Save the file to the local directory*/
                string fileName = Path.GetFileName(postedFile.FileName);
                /*Check file extension*/
                if (fileName.Split(".").Last() != "txt")
                {
                    throw new System.ArgumentException("AnotherExtension");
                }
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                }
                

                /*Read from file and get words*/
                var fileData = System.IO.File.ReadAllText(Path.Combine(path, fileName), Encoding.UTF8);
                if (fileData == "")
                {
                    throw new System.ArgumentException("Empty");
                }
                fileData = Regex.Replace(fileData, @"(\s+'+)|('+\s+)|[(){}\[\]]+", " ");
                var splitWords = Regex.Split(fileData, @"[\s\t\n\r,:;!?.""]+");
                

                /*Count repetitions of words*/
                wordList = splitWords.Where(s => s.Length > 1)
                    .GroupBy(s => s)
                    .Select(s => new WordModel { Word = s.Key, Frequency = s.Count() })
                    .OrderByDescending(wordModel => wordModel.Frequency).ThenBy(x => x.Word).ToList();


                /*Update database with new words*/
                db.WordModels.RemoveRange(db.WordModels);
                db.SaveChanges();
                foreach (var item in wordList)
                {
                    db.WordModels.Add(item);
                    db.SaveChanges();
                }

                if(wordList.Count==0)
                {
                    ViewBag.Message = "There are no words in the file!";
                }
            }
            catch (NullReferenceException)
            {
                ViewBag.Message = "The file was not uploaded!";
            }
            catch (IOException)
            {
                ViewBag.Message = "Sorry, there was a problem loading the file!";
            }
            catch (Exception e){
                ViewBag.Message = e.Message switch
                {
                    "Empty" => "The selected file is empty!",
                    "AnotherExtension" => "Please choose .txt file!",
                    _ => "Application ran into a problem. Please, choose file again.",
                };
            }


            return View("Index", wordList.ToPagedList(1, pageSize));
        }
    }
}

WordCounter/WordCounter/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WordCounter/WordCounter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WordCounter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="UploadFile" asp-action="Index">WordCounter</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> 
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WordCounter - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WordCounter/WordCounter/Views/UploadFile/Index.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@model X.PagedList.IPagedList<WordCounter.Model.WordModel>



@{
    ViewBag.Title = "Read text file";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style type="text/css">
    .localBtn {
        background-color: #007bff;
        border-style: inherit;
        border-color: white;
        color: white;
        border-radius: 20px;
        width: 120px;
        height: 50px;
    }
    .sortStyle {
        float: right;
    }
    .exception {
        color: red;
    }
</style>



@using (Html.BeginForm("Upload", "UploadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table style="padding-top:10px">
        <tr>
            <td colspan="2">
                <h3 style="color: #007bff">Read text file and display the word frequency</h3>
            </td>
        </tr>
        <tr>
            <td style="width: 350px;">
                <input type="file" name="postedFile" />
            </td>
            <td>
                <input type="submit" value="Read Text" class="localBtn" />
            </td>

        </tr>
    </table>

}
<p class="exception">@ViewBag.Message</p>
<hr />
@if (ViewBag.Message == null)
{
    if (Model != null)
    {
    <div>
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("DisplayData", "UploadFile", new { page, sortOrder = ViewBag.SortOrder }),
             new X.PagedList.Mvc.Core.Common.PagedListRenderOptions
             {
                 LiElementClasses = new string[] { "page-item" },
                 PageClasses = new string[] { "page-link" },

             })
    </div>
    <h6>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        <span class="sortStyle">
            @(Html.DropDownList("sortOrder",
                         new SelectList(new string[] { "FrequencyASC", "FrequencyDESC", "WordASC", "WordDESC" }),
                         "Choose sort order", /*ViewBag.SortOrder*/
                         new
                         {
                             onchange = "document.location.href = '/UploadFile/DisplayData?sortOrder=' + this.options[this.selectedIndex].value;",
                             value = (ViewBag.SortOrder != null ? ViewBag.SortOrder : "FrequencyDESC")
                         }))
        </span>
    </h6>


    <table class="table" style="padding-top:10px">

        <thead class="thead-light">

            <tr>
                <th scope="col">Word</th>
                <th scope="col">Frequency</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Word</td>
                    <td>@item.Frequency</td>
                </tr>
            }
        </tbody>
    </table>
        //}
    <div>
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("DisplayData", "UploadFile", new { page, sortOrder = ViewBag.SortOrder }),
             new X.PagedList.Mvc.Core.Common.PagedListRenderOptions
             {
                 LiElementClasses = new string[] { "page-item" },
                 PageClasses = new string[] { "page-link" },

             })
    </div>
    }
}